services:
  jenkins:
    build:
      context: ./microservices/jenkins
      dockerfile: Dockerfile
    container_name: jenkins_service
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/var/jenkins_home/project
      - /var/run/docker.sock:/var/run/docker.sock
      - ./datasets:/var/jenkins_home/workspace
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UpdateCenter.connectionCheckTimeoutMillis=60000
        -Dhudson.model.UpdateCenter.downloadTimeoutMillis=120000
        -Dhudson.model.DownloadService.connectionTimeout=60000
        -Dhudson.model.DownloadService.readTimeout=120000
        -Dhttps.protocols=TLSv1.2
        -Djava.awt.headless=true
    user: root

volumes:
  jenkins_home: