trigger:
  branches:
    include:
      - applications/directus

pool:
  name: TeseMestradoPool

jobs:
  - job: Checkout
    displayName: 'Checkout repository'
    steps:
      - checkout: self
        clean: false
        submodules: true
        displayName: 'Checkout repository'

  - job: InstallDependencies
    displayName: 'Install dependencies'
    dependsOn: Checkout
    steps:
      - script: |
          cd directus && rm -rf node_modules
        displayName: 'Clean dependencies'

      - script: |
          cd directus && pnpm install --frozen-lockfile
        displayName: 'Install dependencies'

  - job: Lint
    displayName: 'Lint'
    dependsOn: InstallDependencies
    steps:

      - script: |
          cd directus && pnpm lint
        displayName: 'Lint'

  - job: Build
    displayName: 'Build'
    dependsOn: Lint
    steps:

      - script: |
          cd directus && pnpm build
        displayName: 'Build'
