global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'jenkins_service'
    metrics_path: /prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
    
  - job_name: 'github-runner-node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9102']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'jenkins-cadvisor'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9103']