services:
  gitlab-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitlab_runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/home/gitlab-runner/.gitlab-runner
      - runner-data:/home/gitlab-runner
      - ..:/workspace:ro
    privileged: true
    ports:
      - "9104:8080" #cAdvisor port
    env_file:
      - .env
    environment:
      - HOME=/home/gitlab-runner
    networks:
      - monitoring

volumes:
  gitlab-runner-config:
  runner-data:

networks:
  monitoring:
