stages:
  - checkout
  - stop-services
  - cleanup
  - deploy
  - status

variables:
  DOCKER_COMPOSE_FILE: "docker-compose.yml"
  MICROSERVICES: "db api-interface job-postings job-reviews data-access"

before_script:
  - echo "Starting CI/CD pipeline for commit $CI_COMMIT_SHORT_SHA"
  - echo "Working directory $(pwd)"

checkout-info:
  stage: checkout
  script:
    - echo "=== CHECKOUT STAGE ==="
    - echo "Building commit $CI_COMMIT_SHORT_SHA"
    - echo "Branch $CI_COMMIT_REF_NAME"
    - echo "Working directory $(pwd)"
  only:
    - main
    - develop

stop-microservices:
  stage: stop-services
  script:
    - echo "=== STOPPING CURRENT MICROSERVICES ==="
    - |
      for service in $MICROSERVICES; do
        docker-compose -f $DOCKER_COMPOSE_FILE stop $service || true
      done
  only:
    - main
    - develop

remove-containers:
  stage: cleanup
  script:
    - echo "=== REMOVING MICROSERVICES CONTAINERS ==="
    - |
      for service in $MICROSERVICES; do
        docker-compose -f $DOCKER_COMPOSE_FILE rm -f $service || true
      done
    - echo "Cleaning unused Docker images..."
    - docker image prune -f || true
  only:
    - main
    - develop

deploy-services:
  stage: deploy
  script:
    - echo "=== BUILDING AND DEPLOYING SERVICES ==="
    - docker-compose up --build -d
    - |
      if [ $? -eq 0 ]; then
        echo "Services built and started successfully"
        echo "Waiting for services to initialize..."
        sleep 15
      else
        echo "ERROR Failed to build and start services"
        exit 1
      fi
  only:
    - main
    - develop

show-status:
  stage: status
  script:
    - echo "=== DEPLOYMENT COMPLETE ==="
    - docker-compose -f $DOCKER_COMPOSE_FILE ps
    - echo "🎉 Deployment successful!"
    - echo "Services status:"
    - echo "- Database http://localhost:5432"
    - echo "- API Interface http://localhost:8082"
    - echo "- Job Postings http://localhost:8081"
    - echo "- Job Reviews http://localhost:8084"
    - echo "- Data Access http://localhost:8083"
    - echo "- GitLab http://localhost:8090"
  only:
    - main
    - develop