services:
  jenkins:
    build:
      dockerfile: Dockerfile
    container_name: jenkins_service
    restart: always
    ports:
      - "8080:8080" # Jenkins web interface
      - "50000:50000"
      - "9103:8081"  # cAdvisor EXPOSED port
      - "5672:5672"  # Expose RabbitMQ port
      - "15672:15672"  # Expose RabbitMQ management UI
      - "8761:8761" # Expose Eureka server port
      - "8000:8000" # Product Service instances
      - "8081:8081" # Product Service instances
      - "8082:8082" # Offer Service
      - "4200:3000" # Microservice UI (Angular)
      - "9102:8080"  # Expose cAdvisor on a unique port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace:ro
      - /sys:/sys:ro  # For cAdvisor system metrics 
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UpdateCenter.connectionCheckTimeoutMillis=60000
        -Dhudson.model.UpdateCenter.downloadTimeoutMillis=120000
        -Dhudson.model.DownloadService.connectionTimeout=60000
        -Dhudson.model.DownloadService.readTimeout=120000
        -Dhttps.protocols=TLSv1.2
        -Djava.awt.headless=true
    user: root
    networks:
      - monitoring

volumes:
  jenkins_home:


networks:
  monitoring: