services:
  jenkins:
    build:
      dockerfile: Dockerfile
    container_name: jenkins_service
    restart: always
    ports:
      - "8080:8080" # Jenkins web interface
      - "50000:50000"
      - "9103:8081"  # cAdvisor EXPOSED port
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/workspace:ro
      - /sys:/sys:ro  # For cAdvisor system metrics
    dns:
      - 8.8.8.8
      - 8.8.4.4 
    environment:
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UpdateCenter.connectionCheckTimeoutMillis=60000
        -Dhudson.model.UpdateCenter.downloadTimeoutMillis=120000
        -Dhudson.model.DownloadService.connectionTimeout=60000
        -Dhudson.model.DownloadService.readTimeout=120000
        -Dhttps.protocols=TLSv1.2
        -Djava.awt.headless=true
    user: root
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512MB

volumes:
  jenkins_home:


networks:
  monitoring: