version: '3.8'

services:
  github-runner:
    build: .
    environment:
      - REPO_URL=${REPO_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-data:/home/runner/_work
    restart: always
    ports:
      - "9102:9100"  # Expose node exporter on a unique port

volumes:
  runner-data:

networks:
  monitoring: