version: '3.8'

services:
  github-runner:
    build: .
    environment:
      - REPO_URL=https://github.com/FredericoPrazeres/teseMestrado
      - RUNNER_TOKEN=${RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-data:/home/runner/_work
    restart: always

volumes:
  runner-data:  