version: '3.8'

services:
  github-runner:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-data:/home/runner/_work
    restart: always

volumes:
  runner-data:  