name: Microservices CI/CD Pipeline (Windows)

on:
  push:
    branches:
      - waitTest

jobs:
  pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Step 1
        run: echo "Step 1 - waiting..."; Start-Sleep -Seconds 3
      - name: Step 2
        run: echo "Step 2 - waiting..."; Start-Sleep -Seconds 3
      - name: Step 3
        run: echo "Step 3 - waiting..."; Start-Sleep -Seconds 3
      - name: Step 4
        run: echo "Step 4 - waiting..."; Start-Sleep -Seconds 3
      - name: Step 5
        run: echo "Step 5 - waiting..."; Start-Sleep -Seconds 3
      - name: Step 6
        run: echo "Step 6 - waiting..."; Start-Sleep -Seconds 3
      - name: Step 7
        run: echo "Step 7 - waiting..."; Start-Sleep -Seconds 3
      - name: Step 8
        run: echo "Step 8 - waiting..."; Start-Sleep -Seconds 3
      - name: Step 9
        run: echo "Step 9 - waiting..."; Start-Sleep -Seconds 3
      - name: Step 10
        run: echo "Step 10 - done!"; Start-Sleep -Seconds 3

